name: paginated-messages
org: sapphire
install: true
packagePath: packages/paginated-messages
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: sapphiredev/utilities
