name: Continuous Delivery - ts-config

on:
    push:
        branches:
            - main
        paths:
            - packages/ts-config/**
            - .all-contributorsrc
            - LICENSE.md
            - package.json
            - .github/workflows/cd-ts-config.yml
jobs:
    BuildTSConfig:
        name: Publish TS config
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Push new code
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                  echo -e "\n# Initialize some useful variables"
                  REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                  BRANCH_OR_TAG=`awk -F/ '{print $2}' <<< $GITHUB_REF`
                  CURRENT_BRANCH=`awk -F/ '{print $NF}' <<< $GITHUB_REF`

                  if [ "$BRANCH_OR_TAG" == "heads" ]; then
                    SOURCE_TYPE="branch"
                  else
                    SOURCE_TYPE="tag"
                  fi

                  echo -e "\n# Move to the tsconfig directory"
                  cd packages/ts-config

                  echo -e "\n# Checkout the repo in the target branch"
                  TARGET_BRANCH="build-tsconfig"
                  git clone $REPO out -b $TARGET_BRANCH

                  echo -e "\n# Remove any old files in the dist folder"
                  rm -rfv out/tsconfig.json

                  echo -e "\n# Move the generated code to the newly-checked-out repo, to be committed and pushed"
                  rsync -vaI package.json out/
                  rsync -vaI ../../.all-contributorsrc out/
                  rsync -vaI ../../LICENSE.md out/
                  rsync -vaI README.md out/
                  rsync -vaI src/tsconfig.json out/

                  echo -e "\n# Commit and push"
                  cd out
                  git add --all .
                  git config user.name "${GITHUB_ACTOR}"
                  git config user.email "${GITHUB_EMAIL}"
                  git commit -m "build: ts-config build for ${GITHUB_SHA}" || true
                  git push origin $TARGET_BRANCH
              env:
                  GITHUB_TOKEN: ${{ secrets.SKYRA_TOKEN }}
                  GITHUB_ACTOR: NM-EEA-Y
                  GITHUB_EMAIL: contact@skyra.pw
